name: C++ Tests

on:
  push:
    paths:
      - 'src/*/*.cpp'
      - 'tests/*/*_test_cases.txt'
      - 'tests/*/*_expected_output.txt'
  pull_request:
    paths:
      - 'src/*/*.cpp'
      - 'tests/*/*_test_cases.txt'
      - 'tests/*/*_expected_output.txt'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up C++ environment
        run: sudo apt-get install g++

      - name: Run Tests
        run: |
          chmod +x run_tests.sh
          ./run_tests.sh
